### PR TITLE
Fix for compatibility with Filament v3

### LINKED ISSUE #6: Not working with filament version 3

### PR DESCRIPTION
**Pull request by eduwass**
Should fix https://github.com/3x1io/filament-commands/issues/6

### CODE REVIEW

**Comment by eduwass** [comment]
Hi @3x1io could you take a look? Thanks!

**Comment by fadymondy** [comment]
this repo is closed for v2 to use v3 you can check this [repo](https://www.github.com/tomatophp/filament-artisan)

**Comment by eduwass** [comment]
Hi @3x1io got it thanks for letting me know! How about adding a note in the readme for future people like me? Also this is listed in the Filament website.

**Comment by fadymondy** [comment]
yes i will thanks for your note @eduwass

**Comment by eduwass** [comment]
No problem, thanks to you for your work!

**Pull request closed without merging**
